version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oncinha
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - oncinha_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/oncinha
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - oncinha_network
    extra_hosts:
      - "backend.localhost.com:127.0.0.1"

  frontend:
    build:
      context: ./oncinhaFront
      dockerfile: Dockerfile.angular
    ports:
      - "4200:4200"
    networks:
      - oncinha_network
    extra_hosts:
      - "angular.localhost.com:127.0.0.1"

volumes:
  db_data:

networks:
  oncinha_network:
    driver: bridge
